  <cdf_var
      name   = "dfb_acdc"
      type   = "integer">
    <cdf_att
        FIELDNAM = "acdc"
        FORMAT = "I08"
        LABLAXIS = "acdc"
        VAR_TYPE = "data"
        DATA_TYPE = "CDF_INT2"
        FILLVAL = "-1.0E31"
        DISPLAY_TYPE = "time_series"
        VALIDMIN = "0"
        VALIDMAX = "1"
        SCALEMIN = "0"
        SCALEMAX = "1"
        UNITS = "None"
        CATDESC = "acdc"
        DEPEND_0 = "epoch">
		</cdf_att>
  </cdf_var>
